### PR TITLE
Introduce usage of AlwaysPullPolicy when pulling images

### PR DESCRIPTION
**Pull request by mchoma**
To avoid undeterministic behaviour.
Details in https://java.testcontainers.org/features/advanced_options/

Local run
```
npm test -- --browser=chrome --specs="cypress/e2e/datasource/test-configuration-datasource-*.cy.ts"
...
 ====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  test-configuration-datasource-maria      00:55        7        7        -        -        - │
  │    db-finder.cy.ts                                                                             │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  test-configuration-datasource-mysql      01:06        7        7        -        -        - │
  │    -finder.cy.ts                                                                               │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  test-configuration-datasource-postg      00:53        7        7        -        -        - │
  │    re-finder.cy.ts                                                                             │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  test-configuration-datasource-postg      00:32        1        1        -        -        - │
  │    re.cy.ts                                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  test-configuration-datasource-sqlse      00:59        7        7        -        -        - │
  │    rver-finder.cy.ts                                                                           │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        04:27       29       29        -        -        -  

```

### CODE REVIEW

**Comment by mchoma** [comment]
Note there is one disadvantage of this change. We definitely need it to avoid undeterministic behaviour. But that mean more often image will be pulled. So often we can find in timeout situation, e.g. `CypressError: cy.task('start:mariadb:container') timed out after waiting 60000ms.`. Tweaking timeouts will be own MR.

**Comment by spriadka** [comment]
LGTM!

**Comment by mchoma** [comment]
Undrafting as I prepared https://github.com/hal/berg/pull/72

**Comment by spriadka** [comment]
LGTM, merging

**Pull request merged**
