### PR TITLE
Add test for EAP7-1984

### PR DESCRIPTION
**Pull request by jedla97**
Hi, this PR adding test coverage for [EAP7-1984](https://issues.redhat.com/browse/EAP7-1984). It's cover added provisioning which was added in [HAL-1827](https://issues.redhat.com/browse/HAL-1827).

The added test coverage should be working only with EAP. When working with WildFly none of these pages should be visible.

#### Homepage test

[HAL-1827](https://issues.redhat.com/browse/HAL-1827) removing the update server by patch command and adding updating by installer command. This PR updating the homepage patch test to homepage update-manager test. This test will run only with EAP as with WildFly this should not be visible.

#### Update-manager

Adding test coverage for installer functions. That is online and offline update from channel, update by custom patch and add/remove/update channel. These test should be run only with EAP server provisioned by installer. With WildFly these function should not be visible and not working.

### CODE REVIEW

**Comment by OndrejKotek** [comment]
@jedla97 Can you update the summary of the PR and and the second commit to be more descriptive please? Something like _"HAL-1827 Adding tests for the new server update mechanism"_ could work.

**Comment by spriadka** [comment]
Please also add `update-manager` into the modules that are executed via GH actions [scheduled-run-all-tests-workflow.yaml](https://github.com/hal/berg/blob/main/.github/workflows/scheduled-run-all-tests-workflow.yaml) and https://github.com/hal/berg/blob/main/.github/workflows/manual-test-matrix-workflow.yaml

**Comment by jedla97** [comment]
PR description updated, commit description updated. Added small change to homepage test because of [JBEAP-24978](https://issues.redhat.com/browse/JBEAP-24978).

@spriadka I added it to GH actions, but it's need to be excluded as this should be only EAP feature and should not work with WildFly.

**Comment by spriadka** [comment]
@jedla97 Okay, rebase please and I'll merge it. We'll adjust the testsuite for EAP specific stuff later

**Pull request merged**
